ALTER TABLE users
  ADD COLUMN IF NOT EXISTS image VARCHAR(255),
  ADD COLUMN IF NOT EXISTS specialization VARCHAR(100),
  ADD COLUMN IF NOT EXISTS location VARCHAR(100),
  ADD COLUMN IF NOT EXISTS rating DECIMAL(2,1) DEFAULT 4.5,
  ADD COLUMN IF NOT EXISTS totalJobs INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS verified BOOLEAN DEFAULT false; 